server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: reactor
  datasource:
    url: jdbc:mysql://localhost:3306/reactor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
     redis:
      host: localhost
      port: 6379
      password: 123456     #如果有密码
      database: 0
      timeout: 6000

logging:
  level:
    org.springframework: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:/com/duanml/reactorservice/**/*.xml